<a href="https://colab.research.google.com/github/AlluNavya/FML/blob/main/Naive_Bayes_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
humidity=['low','high','high','high','low']
sunny=['no','yes','yes','no','yes']
wind=['slow','weak','slow','weak','slow']
play=['no','yes','yes','yes','no']

In [11]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
hum_encoder=le.fit_transform(humidity)
sun_encoder=le.fit_transform(sunny)
wind_encoder=le.fit_transform(wind)
label=le.fit_transform(play)
print("humidity_encoder : ",hum_encoder)#0-high,1-low
print("sunny_encoder : ",sun_encoder)#0-no,1-yes
print("wind_encoder : ",wind_encoder)#0-slow,1-weak
print("label : ",label)#0-no,1-yes

humidity_encoder :  [1 0 0 0 1]
sunny_encoder :  [0 1 1 0 1]
wind_encoder :  [0 1 0 1 0]
label :  [0 1 1 1 0]


In [7]:
import numpy as np
features=np.vstack((hum_encoder,sun_encoder,wind_encoder)).T
print(features)

[[1 0 0]
 [0 1 1]
 [0 1 0]
 [0 0 1]
 [1 1 0]]


In [14]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(features,label)
predicted=model.predict([[1,0,1]])
print(predicted)

[0]
